Webcam.set({
    width:305,
    height:280,
    image_format:'png',
    png_quality:90,
    constraints:{
        facingMode:"environment"
    }
});
camera=document.getElementById("camera");
Webcam.attach('#camera');